<a href="https://colab.research.google.com/github/emdemor/estudos-deep-learning/blob/main/Cursos/Alura/Redes%20Neurais%3A%20Deep%20Learning%20com%20PyTorch/02-Tensores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torch
import numpy as np

In [3]:
# Criando tensor a partir de lista

base_list = [
    [1,2],
    [2,3]
]

base_tensor = torch.Tensor(base_list)

print(base_tensor)

tensor([[1., 2.],
        [2., 3.]])


In [9]:
# Criando tensor a partir de array

base_array = np.array(
  [
    [1,3],
    [2,3]
  ]
)
base_tensor = torch.Tensor(base_array)
print(base_tensor)

base_tensor = torch.from_numpy(base_array) # Essa opção mantem os tipos numpy
print(base_tensor)



tensor([[1., 3.],
        [2., 3.]])
tensor([[1, 3],
        [2, 3]])


In [10]:
# inicialização de tensors
tns1 = torch.ones(2, 3)
tns0 = torch.zeros(3, 5)
tnsr = torch.randn(3, 3)

print(tns1)
print(tns0)
print(tnsr)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[ 0.4623,  0.6928,  2.5569],
        [-0.4862, -1.4056, -1.1394],
        [-0.2211,  0.1708, -0.3343]])


In [12]:
if torch.cuda.is_available():
  device = torch.device('cuda')
else:
  device = torch.device('cpu')
  
print(device)

tns1 = tns1.to(device)

print(tns1)

cpu
tensor([[1., 1., 1.],
        [1., 1., 1.]])
